/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ApplicationsIndexImport } from './routes/applications/index'
import { Route as ApplicationsPostIdImport } from './routes/applications/$postId'

// Create Virtual Routes

const ServersLazyImport = createFileRoute('/servers')()
const PlayersLazyImport = createFileRoute('/players')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const ServersLazyRoute = ServersLazyImport.update({
  path: '/servers',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/servers.lazy').then((d) => d.Route))

const PlayersLazyRoute = PlayersLazyImport.update({
  path: '/players',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/players.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ApplicationsIndexRoute = ApplicationsIndexImport.update({
  path: '/applications/',
  getParentRoute: () => rootRoute,
} as any)

const ApplicationsPostIdRoute = ApplicationsPostIdImport.update({
  path: '/applications/$postId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersLazyImport
      parentRoute: typeof rootRoute
    }
    '/servers': {
      id: '/servers'
      path: '/servers'
      fullPath: '/servers'
      preLoaderRoute: typeof ServersLazyImport
      parentRoute: typeof rootRoute
    }
    '/applications/$postId': {
      id: '/applications/$postId'
      path: '/applications/$postId'
      fullPath: '/applications/$postId'
      preLoaderRoute: typeof ApplicationsPostIdImport
      parentRoute: typeof rootRoute
    }
    '/applications/': {
      id: '/applications/'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  PlayersLazyRoute,
  ServersLazyRoute,
  ApplicationsPostIdRoute,
  ApplicationsIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/players",
        "/servers",
        "/applications/$postId",
        "/applications/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/players": {
      "filePath": "players.lazy.tsx"
    },
    "/servers": {
      "filePath": "servers.lazy.tsx"
    },
    "/applications/$postId": {
      "filePath": "applications/$postId.tsx"
    },
    "/applications/": {
      "filePath": "applications/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
